notifications:
  email:
    recipients:
      - shawn@git.icu
    on_success: change # default: change
    on_failure: always # default: always

language: c

cache: ccache

addons:
  apt:
    packages:
      - python3-dev
      - libiberty-dev
      - clang
      - libavahi-client-dev 

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi

script:
  - ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --without-libiberty; fi
  - make
  - make check

matrix:
  include:
  - os: linux
    compiler: gcc
    dist: trusty
  - os: linux
    compiler: clang
    dist: trusty
